# Configuration for the SIU Lunabotics robot
# This file contains parameters that can be adjusted without recompiling

controller_parser:
  # Joystick control parameters
  joystick_deadzone: 0.1
  turn_sensitivity: 0.5

  # Camera settings
  image_compression_quality: 15
  max_image_width: 640 # Maximum width for images (aspect ratio maintained)
  image_frame_rate: 15

i2c_node:
  bus_id: 1
  heartbeat_interval: 1.0
  command_timeout: 5.0
