# Configuration for the SIU Lunabotics robot
# This file contains parameters that can be adjusted without recompiling

controller_parser:
    # Joystick control parameters
    joystick_deadzone: 0.1
    turn_sensitivity: 0.5

    # Belt speeds (from fastest to slowest)
    belt_speeds: [180, 125, 120]

    # Camera settings
    image_compression_quality: 20

    # Autonomous operation
    auto_dig_duration_seconds: 30

i2c_node:
    bus_id: 1
    heartbeat_interval: 1.0
    command_timeout: 5.0

serial_node:
    port: "/dev/ttyACM0"
    baudrate: 9600
    timeout: 1.0
    write_timeout: 1.0
    retry_interval: 5.0
